from abc import ABC, abstractmethod
from typing import List, Optional
from pydantic import BaseModel, Field


class ActionItemSchema(BaseModel):
    """
    Schema representing a single task assigned during a meeting.
    """
    assignee: Optional[str] = Field(
        None, 
        description="Имя исполнителя (может быть пустым, если исполнитель неизвестен)"
    )
    task: str = Field(
        ..., 
        description="Описание задачи/действия, которое необходимо выполнить"
    )


class MeetingSummarySchema(BaseModel):
    """
    Strict schema representing the structured summary generated by LLMs.
    """
    brief_content: str = Field(
        ..., 
        description="Краткое содержание встречи (общая суть и контекст в несколько абзацев)"
    )
    key_decisions: List[str] = Field(
        default=[],
        description="Основные решения (маркированный список ключевых договоренностей)"
    )
    action_items: List[ActionItemSchema] = Field(
        default=[],
        description="Список конкретных задач в формате Исполнитель -> Задача"
    )
    open_questions: List[str] = Field(
        default=[],
        description="Список тем и вопросов, которые были подняты, но остались без ответа"
    )


class BaseSummaryProvider(ABC):
    """
    Abstract interface for generating structured AI summaries of meetings using LLMs.
    """

    @abstractmethod
    async def generate_summary(self, full_transcript: str) -> MeetingSummarySchema:
        """
        Generates a structured summary based on the full meeting transcript segments.
        
        Args:
            full_transcript: String concatenation of all transcribed meeting segments 
                             with speaker tags and timestamps.
                             
        Returns:
            MeetingSummarySchema: A validated structured summary.
        """
        pass
